import type { Character } from './types'
import { HERO_IMAGES } from '@shared/constants'

export const charactersData: Character[] = [
  {
    id: 'blue-mage',
    name: 'The Blue Mage',
    class: 'Spellcaster',
    type: 'Magic',
    rarity: 'Legendary',
    description: 'Master of the Aether. Controls the flow of time and space.',
    image: HERO_IMAGES['blue-mage'],
    skills: [
      { id: 'chronos', name: 'Chronos Blast', icon: 'chronos', description: 'Deals magic damage and slows the target\'s next turn.', color: 'text-blue-400' },
      { id: 'aether-shield', name: 'Aether Shield', icon: 'aether-shield', description: 'Creates a protective barrier that absorbs incoming spells.', color: 'text-blue-400' },
      { id: 'space-warp', name: 'Space Warp', icon: 'space-warp', description: 'Teleport to any adjacent tile on the board.', color: 'text-blue-400' },
      { id: 'mana-surge', name: 'Mana Surge', icon: 'mana-surge', description: 'Instantly restores mana and increases spell power.', color: 'text-blue-400' },
      { id: 'time-lock', name: 'Time Lock', icon: 'time-lock', description: 'Freezes an enemy in time for 1 turn.', color: 'text-blue-400' },
    ],
  },
  {
    id: 'golden-knight',
    name: 'The Golden Knight',
    class: 'Defender',
    type: 'Melee',
    rarity: 'Legendary',
    description: 'Protector of the Realm. An immovable force with devastating power.',
    image: HERO_IMAGES['golden-knight'],
    skills: [
      { id: 'smite', name: 'Divine Smite', icon: 'smite', description: 'A powerful melee strike that deals extra damage to undead.', color: 'text-gold' },
      { id: 'bastion', name: 'Bastion of Light', icon: 'bastion', description: 'Heals nearby allies and grants them a defense boost.', color: 'text-gold' },
      { id: 'resolve', name: 'Iron Resolve', icon: 'resolve', description: 'Becomes immune to crowd control effects for 2 turns.', color: 'text-gold' },
      { id: 'taunt', name: 'Taunt', icon: 'taunt', description: 'Forces enemies to attack this character.', color: 'text-gold' },
      { id: 'shield-bash', name: 'Shield Bash', icon: 'shield-bash', description: 'Stuns an enemy for 1 turn.', color: 'text-gold' },
    ],
  },
  {
    id: 'assassin',
    name: 'The Assassin',
    class: 'Rogue',
    type: 'Melee',
    rarity: 'Epic',
    description: 'Master of shadows. Strikes from the darkness with lethal precision.',
    image: HERO_IMAGES['assassin'],
    skills: [
      { id: 'shadow-strike', name: 'Shadow Strike', icon: 'shadow-strike', description: 'Attack from stealth for a guaranteed critical hit.', color: 'text-slate-300' },
      { id: 'toxic-blade', name: 'Toxic Blade', icon: 'toxic-blade', description: 'Applies a poison effect that deals damage over time.', color: 'text-slate-300' },
      { id: 'smoke-screen', name: 'Smoke Screen', icon: 'smoke-screen', description: 'Vanishes from sight, making the hero untargetable.', color: 'text-slate-300' },
      { id: 'backstab', name: 'Backstab', icon: 'backstab', description: 'Double damage when attacking from behind.', color: 'text-slate-300' },
      { id: 'vanish', name: 'Vanish', icon: 'vanish', description: 'Become invisible for 2 turns.', color: 'text-slate-300' },
    ],
  },
  {
    id: 'fairy-queen',
    name: 'The Fairy Queen',
    class: 'Nature Guardian',
    type: 'Support',
    rarity: 'Epic',
    description: 'Guardian of the natural world. Heals allies and commands nature\'s fury.',
    image: HERO_IMAGES['fairy-queen'],
    skills: [
      { id: 'floral-heal', name: 'Floral Heal', icon: 'floral-heal', description: 'A potent heal that restores a large amount of HP.', color: 'text-green-400' },
      { id: 'gale-winds', name: 'Gale Winds', icon: 'gale-winds', description: 'Pushes back all enemies in a wide radius.', color: 'text-green-400' },
      { id: 'natures-wrath', name: 'Nature\'s Wrath', icon: 'natures-wrath', description: 'Summons roots to entangle and stun all nearby foes.', color: 'text-green-400' },
      { id: 'blessing', name: 'Nature\'s Blessing', icon: 'blessing', description: 'Grants regeneration to all allies.', color: 'text-green-400' },
      { id: 'entangle', name: 'Entangle', icon: 'entangle', description: 'Roots an enemy preventing movement.', color: 'text-green-400' },
    ],
  },
  {
    id: 'red-warrior',
    name: 'The Red Warrior',
    class: 'Berserker',
    type: 'Melee',
    rarity: 'Legendary',
    description: 'A fearsome warrior whose rage grows with every battle.',
    image: HERO_IMAGES['red-warrior'],
    skills: [
      { id: 'bloodlust', name: 'Bloodlust', icon: 'bloodlust', description: 'Gains attack power for each enemy defeated.', color: 'text-red-400' },
      { id: 'whirlwind', name: 'Whirlwind Strike', icon: 'whirlwind', description: 'Damages all adjacent enemies.', color: 'text-red-400' },
      { id: 'revenge', name: 'Revenge', icon: 'revenge', description: 'Counter-attacks when damaged.', color: 'text-red-400' },
      { id: 'rampage', name: 'Rampage', icon: 'rampage', description: 'Enters a frenzy, increasing damage by 50%.', color: 'text-red-400' },
      { id: 'execute', name: 'Execute', icon: 'execute', description: 'Instantly defeats enemies below 20% HP.', color: 'text-red-400' },
    ],
  },
  {
    id: 'green-druid',
    name: 'The Green Druid',
    class: 'Nature Guardian',
    type: 'Support',
    rarity: 'Epic',
    description: 'A wise keeper of ancient forest secrets.',
    image: HERO_IMAGES['green-druid'],
    skills: [
      { id: 'wild-shape', name: 'Wild Shape', icon: 'wild-shape', description: 'Transforms into a beast for increased stats.', color: 'text-green-400' },
      { id: 'regrowth', name: 'Regrowth', icon: 'regrowth', description: 'Heals an ally over 3 turns.', color: 'text-green-400' },
      { id: 'thorn-wall', name: 'Thorn Wall', icon: 'thorn-wall', description: 'Creates a barrier that damages attackers.', color: 'text-green-400' },
      { id: 'moonfire', name: 'Moonfire', icon: 'moonfire', description: 'Burns enemies with lunar energy.', color: 'text-green-400' },
      { id: 'tranquility', name: 'Tranquility', icon: 'tranquility', description: 'Heals all allies over 5 turns.', color: 'text-green-400' },
    ],
  },
  {
    id: 'white-cleric',
    name: 'The White Cleric',
    class: 'Holy Priest',
    type: 'Support',
    rarity: 'Rare',
    description: 'A devoted healer blessed by divine light.',
    image: HERO_IMAGES['white-cleric'],
    skills: [
      { id: 'divine-light', name: 'Divine Light', icon: 'divine-light', description: 'Heals all allies in a radius.', color: 'text-white' },
      { id: 'purify', name: 'Purify', icon: 'purify', description: 'Removes all debuffs from an ally.', color: 'text-white' },
      { id: 'holy-shield', name: 'Holy Shield', icon: 'holy-shield', description: 'Grants immunity to magic damage.', color: 'text-white' },
      { id: 'resurrection', name: 'Resurrection', icon: 'resurrection', description: 'Revives a fallen ally with 50% HP.', color: 'text-white' },
      { id: 'smite-evil', name: 'Smite Evil', icon: 'smite-evil', description: 'Deals extra damage to dark enemies.', color: 'text-white' },
    ],
  },
  {
    id: 'black-necromancer',
    name: 'The Black Necromancer',
    class: 'Dark Mage',
    type: 'Magic',
    rarity: 'Legendary',
    description: 'A master of death magic who commands the undead.',
    image: HERO_IMAGES['black-necromancer'],
    skills: [
      { id: 'raise-dead', name: 'Raise Dead', icon: 'raise-dead', description: 'Summons an undead minion to fight.', color: 'text-purple-400' },
      { id: 'life-drain', name: 'Life Drain', icon: 'life-drain', description: 'Steals HP from an enemy.', color: 'text-purple-400' },
      { id: 'curse', name: 'Curse of Weakness', icon: 'curse', description: 'Reduces enemy damage by 50%.', color: 'text-purple-400' },
      { id: 'death-coil', name: 'Death Coil', icon: 'death-coil', description: 'Damages an enemy and heals self.', color: 'text-purple-400' },
      { id: 'lich-form', name: 'Lich Form', icon: 'lich-form', description: 'Becomes immortal for 2 turns.', color: 'text-purple-400' },
    ],
  },
]
